"""Emit road-graph fixtures from the Python baseline for the Swift tests.

Samples points along the real recorded drive and records what the Python
`RoadNetwork` says about each of them, so the Swift loader can be checked
against it rather than against my own expectations.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "processor" / "src"))

from geotrace.coordinates import LocalFrame  # noqa: E402
from geotrace.loader import load_trip  # noqa: E402
from geotrace.road_graph import RoadNetwork, clip_graph, load_graph  # noqa: E402

TRIP = ROOT / "trip-8cd9b15c-bac6-4b59-8a16-f1e217b01e47"
GRAPH = ROOT / "cache/spb.graphml"
RADIUS = 12_000.0
OUT = ROOT / "ios/LiveTracking/Tests/LiveTrackingTests/GraphFixtures.swift"


def main() -> None:
    trip, _ = load_trip(TRIP)
    fixes = trip.usable_locations
    origin = fixes[0]
    frame = LocalFrame(origin.latitude, origin.longitude)
    network = RoadNetwork(
        clip_graph(load_graph(GRAPH), origin.latitude, origin.longitude, RADIUS), frame
    )
    print(f"python network: {len(network)} edges")

    rows = []
    step = max(1, len(fixes) // 40)
    for fix in fixes[::step]:
        xy = frame.to_local(fix.latitude, fix.longitude)
        distance = network.distance_to_road(xy)
        snapped = network.snap(xy, k=6)
        s, offset = (snapped[1], snapped[2]) if snapped else (0.0, distance)
        position = network.edges[snapped[0]].position(s) if snapped else (0.0, 0.0)
        bearing = network.edges[snapped[0]].bearing(s) if snapped else 0.0
        rows.append(
            {
                "lat": fix.latitude,
                "lon": fix.longitude,
                "east": xy[0],
                "north": xy[1],
                "distance": distance,
                "snap_offset": offset,
                "snap_east": position[0],
                "snap_north": position[1],
                "snap_bearing": bearing,
            }
        )

    body = "\n".join(
        "        .init(lat: {lat!r}, lon: {lon!r}, east: {east!r}, north: {north!r}, "
        "distanceToRoad: {distance!r}, snapOffset: {snap_offset!r}, "
        "snapEast: {snap_east!r}, snapNorth: {snap_north!r}, snapBearing: {snap_bearing!r}),".format(**r)
        for r in rows
    )
    OUT.write_text(
        f'''// Generated by tools/dump_graph_fixtures.py - do not edit by hand.
//
// The Python RoadNetwork is the reference. Every value here comes from
// clipping cache/spb.graphml to {RADIUS:.0f} m around the first fix of the real
// recorded drive and asking the baseline what it sees.

enum GraphFixtures {{
    struct Sample {{
        let lat: Double, lon: Double
        let east: Double, north: Double
        let distanceToRoad: Double
        let snapOffset: Double
        let snapEast: Double, snapNorth: Double
        let snapBearing: Double
    }}

    static let originLatitude = {origin.latitude!r}
    static let originLongitude = {origin.longitude!r}
    static let radiusM = {RADIUS!r}
    static let pythonEdgeCount = {len(network)}

    static let samples: [Sample] = [
{body}
    ]
}}
''',
        encoding="utf-8",
    )
    print(f"wrote {OUT} with {len(rows)} samples")


if __name__ == "__main__":
    main()
