"""Emit parity-RNG fixtures so Swift can prove it draws the same numbers.

The whole point of `geotrace.parity_rng` is that another language can reproduce
it exactly. That claim is only worth anything if it is checked, so the expected
values are generated here from the Python implementation and asserted on the
Swift side.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "processor" / "src"))

from geotrace.parity_rng import ParityGenerator  # noqa: E402

OUT = ROOT / "ios/LiveTracking/Tests/LiveTrackingTests/RNGFixtures.swift"


def main() -> None:
    g = ParityGenerator(42)
    uint32s = [int(g._next_uint32()) for _ in range(8)]

    g = ParityGenerator(42)
    doubles = [float(g.random()) for _ in range(6)]

    g = ParityGenerator(42)
    normals = [float(x) for x in g.normal(0.0, 1.0, 7)]

    g = ParityGenerator(42)
    scaled = [float(x) for x in g.normal(2.5, 0.25, 4)]

    g = ParityGenerator(7)
    ints = [int(g.integers(11)) for _ in range(8)]

    g = ParityGenerator(7)
    weights = [0.1, 0.2, 0.3, 0.4]
    choices = [int(g.choice(4, p=weights)) for _ in range(10)]

    g = ParityGenerator(7)
    counts = [int(x) for x in g.multinomial(50, [0.5, 0.2, 0.2, 0.1])]

    # A mixed sequence: the consumption *order* is the part that has to match.
    g = ParityGenerator(99)
    mixed = []
    mixed.extend(float(x) for x in g.normal(0.0, 1.0, 3))   # odd count: burns a pair
    mixed.append(float(g.random()))
    mixed.append(float(g.integers(5)))
    mixed.append(float(g.normal(0.0, 1.0)))                 # scalar: burns a pair
    mixed.extend(float(x) for x in g.normal(0.0, 2.0, 2))

    def fmt(values) -> str:
        return ", ".join(repr(v) for v in values)

    OUT.write_text(
        f'''// Generated by tools/dump_rng_fixtures.py - do not edit by hand.
//
// Expected values from geotrace.parity_rng.ParityGenerator, the Python side of
// the cross-language generator. If these ever disagree, the two particle
// filters are no longer drawing the same numbers and every parity claim about
// them is void.

enum RNGFixtures {{
    static let uint32Seed42: [UInt32] = [{fmt(uint32s)}]
    static let doublesSeed42: [Double] = [{fmt(doubles)}]
    static let normalsSeed42: [Double] = [{fmt(normals)}]
    static let scaledNormalsSeed42: [Double] = [{fmt(scaled)}]
    static let integersSeed7: [Int] = [{fmt(ints)}]
    static let choicesSeed7: [Int] = [{fmt(choices)}]
    static let multinomialSeed7: [Int] = [{fmt(counts)}]
    static let mixedSeed99: [Double] = [{fmt(mixed)}]
}}
''',
        encoding="utf-8",
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
