"""Emit cross-language projection fixtures from the Python baseline.

The Python `LocalFrame` (pyproj `+proj=aeqd +datum=WGS84`) is the reference.
This writes the expected ENU values as a Swift source file so the Swift tests
fail loudly if the two projections ever drift apart.

    processor/.venv/bin/python tools/dump_projection_fixtures.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "processor" / "src"))

from geotrace.coordinates import LocalFrame  # noqa: E402

ORIGIN = (59.9311, 30.3609)
POINTS = [
    (59.9311, 30.3609),   # the origin itself
    (59.9400, 30.3700),   # a few hundred metres away
    (59.9390, 30.3158),   # Palace Square
    (59.9269, 30.3497),   # Sennaya
    (59.8500, 30.2000),   # ~13 km south-west
    (60.0500, 30.5500),   # ~17 km north-east
    (59.6468, 29.4431),   # graph corner, ~60 km out
    (60.2441, 30.7274),   # opposite graph corner
    (59.9311, 30.4609),   # due east
    (59.9811, 30.3609),   # due north
]

OUT = Path(__file__).resolve().parents[1] / (
    "ios/LiveTracking/Tests/LiveTrackingTests/ProjectionFixtures.swift"
)


def main() -> None:
    frame = LocalFrame(*ORIGIN)
    rows = []
    for lat, lon in POINTS:
        east, north = frame.to_local(lat, lon)
        rows.append(
            f"        (lat: {lat!r}, lon: {lon!r}, "
            f"east: {east!r}, north: {north!r}),"
        )
    body = "\n".join(rows)
    OUT.write_text(
        f'''// Generated by tools/dump_projection_fixtures.py - do not edit by hand.
//
// Expected values come from the Python baseline's LocalFrame
// (pyproj "+proj=aeqd +datum=WGS84"), which is the reference implementation.

enum ProjectionFixtures {{
    static let originLatitude = {ORIGIN[0]!r}
    static let originLongitude = {ORIGIN[1]!r}

    /// (latitude, longitude) -> (east, north) in metres, from Python.
    static let points: [(lat: Double, lon: Double, east: Double, north: Double)] = [
{body}
    ]
}}
''',
        encoding="utf-8",
    )
    print(f"wrote {OUT} with {len(POINTS)} fixtures")


if __name__ == "__main__":
    main()
