// Generated by tools/dump_projection_fixtures.py - do not edit by hand.
//
// Expected values come from the Python baseline's LocalFrame
// (pyproj "+proj=aeqd +datum=WGS84"), which is the reference implementation.

enum ProjectionFixtures {
    static let originLatitude = 59.9311
    static let originLongitude = 30.3609

    /// (latitude, longitude) -> (east, north) in metres, from Python.
    static let points: [(lat: Double, lon: Double, east: Double, north: Double)] = [
        (lat: 59.9311, lon: 30.3609, east: 0.0, north: 0.0),
        (lat: 59.94, lon: 30.37, east: 508.69919430990814, north: 991.5945651539495),
        (lat: 59.939, lon: 30.3158, east: -2521.2112793688557, north: 881.0071081073476),
        (lat: 59.9269, lon: 30.3497, east: -626.3382206527326, north: -467.87355759146516),
        (lat: 59.85, lon: 30.2, east: -9018.82640779306, north: -9024.429188165228),
        (lat: 60.05, lon: 30.55, east: 10535.847250558674, north: 13261.954451105179),
        (lat: 59.6468, lon: 29.4431, east: -51756.70671622942, north: -31315.077952086445),
        (lat: 60.2441, lon: 30.7274, east: 20299.854976240582, north: 34928.75847502469),
        (lat: 59.9311, lon: 30.4609, east: 5591.596672891961, north: 4.222911791611941),
        (lat: 59.9811, lon: 30.3609, east: 0.0, north: 5570.577050180881),
    ]
}
