// Generated by tools/dump_rng_fixtures.py - do not edit by hand.
//
// Expected values from geotrace.parity_rng.ParityGenerator, the Python side of
// the cross-language generator. If these ever disagree, the two particle
// filters are no longer drawing the same numbers and every parity claim about
// them is void.

enum RNGFixtures {
    static let uint32Seed42: [UInt32] = [1898997482, 1014631766, 4096008554, 633901381, 1139273534, 2429548044, 1379009937, 1407171768]
    static let doublesSeed42: [Double] = [0.44214480608614093, 0.9536763080739397, 0.2652577903507447, 0.3210757713130751, 0.45017614880225454, 0.27301324463907506]
    static let normalsSeed42: [Double] = [1.223854529143001, -0.3666275514122798, -0.7036031356541884, 1.469370236411195, -0.1820502925469162, 1.250236118915241, -1.5453064586318392]
    static let scaledNormalsSeed42: [Double] = [2.80596363228575, 2.40834311214693, 2.324099216086453, 2.8673425591027986]
    static let integersSeed7: [Int] = [5, 8, 6, 9, 2, 5, 3, 8]
    static let choicesSeed7: [Int] = [3, 3, 3, 2, 3, 2, 2, 3, 2, 1]
    static let multinomialSeed7: [Int] = [23, 8, 10, 9]
    static let mixedSeed99: [Double] = [0.0829853658971896, -0.2427676111165207, -0.9378614133233354, 0.21928526578140384, 4.0, -0.47513252962543473, 1.1509369139223662, -0.5919431823380277]
}
